### ISSUE TITLE
Fabric 1.19 Bug players kicked from the server

### ISSUE THREAD

**Issue by MrJorman** [nu11une/wardenloot#12]
If I hit a player in a bib with tools from the mod, then it crashes when the bib is activated with this error
![image](https://user-images.githubusercontent.com/55187962/179637895-37b12f76-1ae2-4509-9481-7e20bf045e1d.png)

**Comment by nu11une** [comment]
What do you mean by 'bib'? Please paste the `latest.log` from this crash

**Comment by nu11une** [comment]
Closing because of no response
