### ISSUE TITLE
Armor is bugged

### ISSUE THREAD

**Issue by princep444** [nu11une/wardenloot#13]
**Describe the bug**
The armor looks glitched and distorted.

**To Reproduce**
1. Put on the armor

**Expected behavior**
I expected the armor to not look like this 

**Screenshots**

![2022-07-28_12 39 23](https://user-images.githubusercontent.com/32205338/181592138-950873e5-49f0-4c6f-8e63-6de01e1368be.png)

**Modloader(s)**
 - [x] Fabric
 - [ ] Forge

**Additional context**
These are the mods I have installed.

- actuallyunbreaking 1.19-0.1.0
	- additionalbars 3.3.1+1.19
	- adorn 3.6.1+1.19
	- advanced-xray-fabric 1.19-1.1.0-build.12
	- adventurez 1.4.14
	- allstackable v1.5.6-1.19
	- animal_feeding_trough 1.0.3+1.19
	- appleskin 2.4.0+mc1.19
	- architectury 5.10.33
	- artifacts 7.1.1+fabric
	- backslot 1.2.8
	- backslotaddon 1.0.9
	- badpackets 0.1.2
	- bclib 2.0.17
	- beaconoverhaul 1.7.0+1.19
	- besmirchment 1.19-2
	- betteradvancements 0.2.2.136
	- betterbiomeblend 1.19-1.3.6-fabric
	- betterend 2.0.10
	- betterfpsdist 1.19-1.9
	- betternether 7.0.7
	- betterthirdperson 1.8.1
	- bettertridentreturn 1.19-1.0.2
	- bewitchment 1.19-4
	- bigbeacons 1.2.6
	- blur 2.6.0
	- bookshelf 14.1.7
	- bwplus 1.19-4
	- cacao 1.2
	- cardinal-components 5.0.1
	- cem 0.7.1
	- cleancut 1.19-5.0-fabric
	- clear-skies 2.0.94
	- cloth-api 4.0.65
	- cloth-config 7.0.73
	- clumps 9.0.0+7
	- collective-fabric 4.27
	- complete_bone_meal 1.4.0
	- completeconfig 2.0.0
	- controlling 10.0+3
	- couplings 1.9.0+1.19
	- cpm 0.4.4a
	- crawl 0.11.0
	- crops_love_rain 1.3.0
	- croptopia 2.0.7
	- cryingportals-fabric 1.3
	- cullleaves 2.3.4
	- dashloader 4.0.0+1.19
	- despawningeggshatch-fabric 2.5
	- disable_custom_worlds_advice 3.0
	- dragondropselytra-fabric 1.6
	- earthtojavamobs 1.9.2
	- editsign 2.4.2
	- effective 1.2.2
	- egg-of-capitalism 3.1
	- enchant_the_rainbow 1.1.0
	- enchdesc 11.0.4
	- enderitemod 1.4.1
	- enderitestorage 1.0.2+1.19
	- enderscape 0.3.4-1.19
	- endportalrecipe-fabric 2.7
	- enhancedblockentities 0.7.1+1.19
	- enhancedcelestials 2.0.0.0
	- entity_texture_features 4.0.1
	- entitycollisionfpsfix 2.0.0.0
	- entityculling 1.5.2-mc1.19
	- extremesoundmuffler 3.30_fabric-1.19
	- fabric 0.58.0+1.19
	- fabricenchantments 0.8.0
	- fabricloader 0.14.8
	- fallingtree 3.7.4
	- fastload 1.1.5
	- ferritecore 4.2.1
	- forgeconfigapiport 4.0.1
	- forgetmechunk 1.0.4-1.18.X-1.19.X
	- frameless 1.0.1
	- friendsandfoes 1.5.5
	- fwaystones 3.0.2+mc1.19
	- geckolib3 3.1.6
	- goldensteak 1.0.5-1.19
	- haema 1.10.2+1.19
	- horsestatsvanilla 4.2.2
	- hugestructureblocks 1.0.6
	- icarus 1.13
	- iceberg 1.0.38
	- illuminations 1.10.8
	- impaled 1.1.4
	- incantationem 1.1.4+1.19
	- indium 1.0.6+mc1.19
	- inventorysorter 1.8.10-1.19
	- iris 1.2.6
	- jamlib 0.3.2
	- java 17
	- justneeded fabric-1.19-fabric-1.0.1
	- lambdabettergrass 1.3.0+1.19
	- lazydfu 0.1.3
	- lcsl 1.1.0
	- legendarytooltips 1.2.6
	- lithium 0.8.1
	- malilib 0.13.0
	- mavm 1.1.0
	- mca 7.3.11+1.19
	- megane 8.2.0
	- memoryleakfix 1.19-0.5.4
	- mermod 1.9
	- midashunger 2.1.0+1.19.0
	- minecraft 1.19
	- missingwilds 1.1.2
	- mo_glass 1.6.1-MC1.19
	- mob_catcher 1.2.4
	- modmenu 4.0.4
	- moenchantments 2.2.5+1.19
	- more-axolotls 1.0.2
	- moreberries 1.5.1
	- mousetweaks 2.22
	- naturescompass 1.19-2.0.4-fabric
	- nbteditor 1.6.1
	- notenoughanimations 1.6.0
	- npcvariety 2.2.1

**Comment by nu11une** [comment]
It looks like MoreMcmeta isn't in the mods list. Either install MoreMcmeta or disable the animated armor option in the config and this should be fixed.
