### ISSUE TITLE
[Request] Alternate version suggestion

### ISSUE THREAD

**Issue by ConqAra** [nu11une/wardenloot#2]
I really would like it if there was an alternative version of the mod (whether a config or actual version) that only had the chestplate, and to make it so the only way to obtain it is to kill the warden and obtain the heart. No optional ways of obtaining it through chance or being able to craft it, just get a heart after killing it and upgrade the netherite chestplate only, since it's main feature is its chest. I like the idea of the warden loot just being simple and only that chest upgrade, nothing else.

**Comment by nu11une** [comment]
I'm planning on adding a config in the future, so I'll add that as an option when I do. Thanks for the suggestion!

**Comment by nu11une** [comment]
Config added in version 1.0.1-1.19 👍
