### ISSUE TITLE
[Bug 1.19 Fabric] Configuration of attributes for each item

### ISSUE THREAD

**Issue by MrJorman** [nu11une/wardenloot#8]
Please output the configuration of armor attributes and tools for each separately, with knockback resistance, protection and armor hardness, since it is not very convenient to edit this, it turns out that an unloaded breastplate has very little armor.

Fabric 1.19

**Comment by MrJorman** [comment]
I would like to specify the attribute I need for each item, on my server where players play - this armor is considered too powerful, I would like to reduce attributes, I have attributes in configurations, but I can't change my attributes for each breastplate, as well as knockback resistance, please, fix it.

**Comment by MrJorman** [comment]
And I changed the textures of almost all items and armor

![image](https://user-images.githubusercontent.com/55187962/178393437-b62dcadd-9a77-4a4f-bce5-c8ac57ab32f8.png)

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/178393512-72a69422-5645-4280-8474-5f446e683617.png)

**Comment by nu11une** [comment]
I'm not sure what the problem is. Are you asking for options to edit the stats of each individual armor piece?

**Comment by MrJorman** [comment]
> I'm not sure what the problem is. Are you asking for options to edit the stats of each individual armor piece?

yess

**Comment by MrJorman** [comment]
Also, please output in the configuration the chance of falling out of souls and their number.

**Comment by nu11une** [comment]
I'm going to keep the config options as-is for now for the sake of simplicity

**Comment by MrJorman** [comment]
> I'm going to keep the config options as-is for now for the sake of simplicity

i delete your mod from my server..

**Comment by MrJorman** [comment]
You cannot normally output the configuration of items.
