### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by eliasssssssssss** [nu11une/wardenloot#9]
when i put the new mod that looks awsome to play with i load into the game i load up a world and when im in creative i will try to see the cool items this mod comes with and as i do that there is nothing in the warden loot items it is blank with a black and purple logo and every time i press escape to either change a setting or somthing etc the game crashes completely with an error code of -1 i can not solve this problem please help

**Comment by nu11une** [comment]
Could you [paste the crash report](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report) into [pastebin](https://pastebin.com/index.php) and then link it?

**Comment by nu11une** [comment]
Closing this issue since it isn't a bug or suggestion. Join the [discord](https://discord.gg/MDN2njJGhT) if you need help
